filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /apps/svr/server/*/log.file
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
    max_lines: 1000
    timeout: 3s
output.elasticsearch:
  hosts: ["127.0.0.1:19200"]
  index: "log-%{+yyyy.MM}"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
